In [32]:
# Importing all necessary libraries for this project
import numpy as np
import random
from time import sleep

# Function to create an empty Tic-tac-toe board
def empty_board():
    board = np.array([
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]
    ])
    return board

# Function to check for empty places on the Tic-Tac-Toe board
def empty_places(board):
    l = []
    for i in range(len(board)):
        for j in range(len(board)):
            if board[i][j] == 0:
                l.append((i, j))
    return l

# Function to place the player's move randomly on the board
def random_place(board, player):
    select = empty_places(board)
    current_location = random.choice(select)
    board[current_location] = player
    return board

# Checks whether the player has three of their marks in a horizontal row
def row_winner(board, player):
    for x in range(len(board)):
        win = True
        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                break
        if win:
            return win
    return False

# Checks whether the player has three of their marks in a vertical row
def col_winner(board, player):
    for x in range(len(board)):
        win = True
        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                break
        if win:
            return win
    return False

# Checks whether the player has three of their marks in a diagonal row
def diag_winner(board, player):
    win = True
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
            break
    if win:
        return win

    win = True
    for x in range(len(board)):
        y = len(board) - 1 - x
        if board[x, y] != player:
            win = False
            break
    return win

# Evaluates whether there is a winner or a tie
def evaluate_game(board):
    # Winner: [0 = indecisive; 1 = Player 1; 2 = Player 2; -1 = Tie]
    winner = 0
    for player in [1, 2]:
        if (row_winner(board, player) or
            col_winner(board, player) or
            diag_winner(board, player)):
            winner = player
            break
    if np.all(board != 0) and winner == 0:
        winner = -1  # Tie
    return winner

# Main function to simulate the Tic-Tac-Toe game
def tic_tac_toe():
    board = empty_board()  # Initialize the board
    winner = 0  # Initialize winner
    counter = 1  # Move counter

    print("Initial board:")
    print(board)
    sleep(2)

    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print(f"Board after move {counter} by player {player}:")
            print(board)
            sleep(2)

            counter += 1
            winner = evaluate_game(board)

            if winner != 0:
                break

    return winner

# Driver Code
print("Winner is player: " + str(tic_tac_toe()))


Initial board:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after move 1 by player 1:
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Board after move 2 by player 2:
[[1 0 0]
 [0 2 0]
 [0 0 0]]
Board after move 3 by player 1:
[[1 0 0]
 [0 2 0]
 [0 1 0]]
Board after move 4 by player 2:
[[1 0 0]
 [0 2 0]
 [0 1 2]]
Board after move 5 by player 1:
[[1 1 0]
 [0 2 0]
 [0 1 2]]
Board after move 6 by player 2:
[[1 1 0]
 [0 2 0]
 [2 1 2]]
Board after move 7 by player 1:
[[1 1 1]
 [0 2 0]
 [2 1 2]]
Winner is player: 1
